on:
  workflow_call:
    inputs:
      example_program:
        required: true
        type: string
      k8s_cluster_ver:
        required: true
        type: string
      k8s_package_ver:
        required: true
        type: string

jobs:
  test-one:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.22.10"
    - name: Create test Kubernetes cluster (using kind)
      uses: helm/kind-action@v1.5.0
      with:
        node_image: kindest/node:v${{ inputs.k8s_cluster_ver }}
    - name: Run mini-program ${{ inputs.example_program }} on Kubernetes v${{ inputs.k8s_cluster_ver }} using client-go v${{ inputs.k8s_package_ver }}
      run: |
        cd ${{ inputs.example_program }}
        go mod edit -replace k8s.io/client-go=k8s.io/client-go@v${{ inputs.k8s_package_ver }}
        go mod edit -replace k8s.io/api=k8s.io/api@v${{ inputs.k8s_package_ver }}
        go mod edit -replace k8s.io/apimachinery=k8s.io/apimachinery@v${{ inputs.k8s_package_ver }}
        go mod edit -replace k8s.io/cli-runtime=k8s.io/cli-runtime@v${{ inputs.k8s_package_ver }}
        go mod tidy
        make test
